// chat-client/src/components/MessageBubble.jsx
import React from "react";
import { formatMessageTime } from "../utils/formatTime";
import { useChatContext } from "../context/ChatContext.jsx";


const MessageBubble = ({ message }) => {
  const { currentUser } = useChatContext();

  // const { text, image, isSelf, timestamp } = message; Hình ảnh chưa có nên tạm thời ẩn đi, sau này sửa lại
  const { NoiDung, MaNguoiGui, NgayGuiTinNhan } = message;
  const time = formatMessageTime(NgayGuiTinNhan);

  
  const isSelf = MaNguoiGui === currentUser?.id; 

  if (isSelf) {
    return (
      <div className="message-bubble flex mb-4 justify-end">
        <div className="message-content max-w-xs lg:max-w-md px-4 py-2 rounded-2xl bg-primary text-white">
          {/* {image && (
            <p className="mb-2">
              <img src={image} alt="shared" className="rounded-lg max-w-full h-auto" />
            </p>
          )} */}
          {NoiDung && <p className="text-sm whitespace-pre-wrap">{NoiDung}</p>}
          <p className="text-xs mt-1 text-white/70">{time}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="message-bubble flex mb-4 justify-start">
      <div className="message-content max-w-xs lg:max-w-md px-4 py-2 rounded-2xl bg-white text-gray-800">
        {/* {image && (
          <p className="mb-2">
            <img src={image} alt="shared" className="rounded-lg max-w-full h-auto" />
          </p>
        )} */}
        {NoiDung && <p className="text-sm whitespace-pre-wrap">{NoiDung}</p>}
        <p className="text-xs mt-1 text-gray-500">{time}</p>
      </div>
    </div>
  );
};

export default MessageBubble;

// client/src/components/MessageBubble.vue
<template>
  <div
    class="message-bubble flex mb-4"
    :class="{ 'justify-end': isSent, 'justify-start': !isSent }"
  >
    <div
      class="message-content max-w-xs lg:max-w-md px-4 py-2 rounded-2xl"
      :class="isSent ? 'bg-primary text-white' : 'bg-white text-gray-800'"
    >
      <p v-if="message.image" class="mb-2">
        <img
          :src="message.image"
          :alt="message.content"
          class="rounded-lg max-w-full h-auto"
        />
      </p>
      <p class="text-sm whitespace-pre-wrap">{{ message.content }}</p>
      <p
        class="text-xs mt-1"
        :class="isSent ? 'text-white/70' : 'text-gray-500'"
      >
        {{ formatTime(message.timestamp) }}
      </p>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { Message } from '../types/messageType';
import { computed } from 'vue';

const props = defineProps<{
  message: Message;
  currentUserId: string;
}>();

const isSent = computed(() => props.message.senderId === props.currentUserId);

const formatTime = (timestamp: string) => {
  const date = new Date(timestamp);
  const hours = date.getHours().toString().padStart(2, '0');
  const minutes = date.getMinutes().toString().padStart(2, '0');
  return `${hours}:${minutes}`;
};
</script>

<style scoped>
.message-content {
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
}
</style>
